name: Docker Image CI

on:
  push:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Build the Docker image
        run: |
          docker login -p ${{ secrets.GITHUBTOKEN }} -u ${{ secrets.GITHUBNAME }} ghcr.io
          docker build . --file Dockerfile --tag ghcr.io/alinavlasova1/nebus:latest
          docker push ghcr.io/alinavlasova1/nebus:latest
#      - name: Run Docker Compose
#        run: docker compose -f docker-compose.yml up -d

  deploy:
    name: Deploy Application  # Defines the name of the deployment job.

    # Add a dependency to the build job
    needs: build_and_push  # Specifies that the deployment job depends on the successful completion of the build job.

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # Grants write permission to deploy to Pages.
      id-token: write   # Grants write permission to verify the deployment source.

    environment:
      name: production  # Specifies the environment for deployment.
      url: ${{ steps.deployment.outputs.page_url }}  # Retrieves the deployment URL from the previous deployment step.

    runs-on: ubuntu-latest  # Specifies the operating system for the deployment job.
    steps:
      - name: Deploy to GitHub Pages  # Deploys the application to GitHub Pages.
        id: deployment
        uses: actions/deploy-pages@v2