name: Docker Image CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Build the Docker image
        run: |
          docker login  -p ${{ secrets.GITHUBTOKEN }} -u ${{ secrets.GITHUBNAME }} ghcr.io
          docker build . --file Dockerfile --tag ghcr.io/alinavlasova1/nebus:latest
          docker push ghcr.io/alinavlasova1/nebus:latest
      - name: Run Docker Compose
        run: docker compose -f docker-compose.yml up -d
