name: Docker Image CI

on:
  push:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker login  -p ${{ secrets.GITHUBTOKEN }} -u ${{ secrets.GITHUBNAME }} ghcr.io
          docker build . --file Dockerfile --tag ghcr.io/alinavlasova1/nebus:latest
          docker push ghcr.io/alinavlasova1/nebus:latest
          docker run -d --name nebus-container ghcr.io/alinavlasova1/nebus:latest

  Deploy:
    needs: build_and_publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUBNAME }}
          password: ${{ secrets.GITHUBTOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/alinavlasova1/nebus:latest