name: Docker Image CI

on:
  push:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Build the Docker image
        run: |
          docker login -p ${{ secrets.GITHUBTOKEN }} -u ${{ secrets.GITHUBNAME }} ghcr.io
          docker build . --file Dockerfile --tag ghcr.io/alinavlasova1/nebus:latest
          docker push ghcr.io/alinavlasova1/nebus:latest
#      - name: Run Docker Compose
#        run: docker compose -f docker-compose.yml up -d

  deploy:
    name: Deploy Application  # Defines the name of the deployment job.

    # Add a dependency to the build job
    needs: build_and_push  # Specifies that the deployment job depends on the successful completion of the build job.
  # Retrieves the deployment URL from the previous deployment step.

    runs-on: ubuntu-latest  # Specifies the operating system for the deployment job.
    steps:
      - name: Deploy to GitHub Pages  # Deploys the application to GitHub Pages.
        run: |
          docker run --rm -it -p 4000:4000 -v /mysite:/site --entrypoint /bin/sh madduci/docker-github-pages -c "bundle install && bundle exec jekyll serve --watch --force_polling --host 0.0.0.0"