name: Docker Image CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker login  -p ${{ secrets.GITHUBTOKEN }} -u ${{ secrets.GITHUBNAME }} ghcr.io
          docker build . --file Dockerfile --tag ghcr.io/alinavlasova1/nebus:latest
          docker push ghcr.io/alinavlasova1/nebus:latest
          docker-compose up -d
